#include <stdlib.h>
#include <fstream>
#include <iostream>
#include <math.h>
#include <assert.h>
#include <string.h>

using namespace std;
using namespace __gnu_cxx;


// parameters for identifying suspicious or good regions:
//
// the min size of suspicious or good regions
int MIN_SEG_SIZE = 50;
// the pvalue threshold for suspicious regions
float PVTHRESH_BAD = 0.1;
// the pvalue threshold for good regions
float PVTHRESH_GOOD = 1e-10;


// ****************** No change below *********************

int chr_len;
int CHR_START;
int ALIGN_LEN;
int MAX_BLOCK_SIZE = 1000000;

// the .maf file
char mafFile[100] = "";
// the directory that contains output files generated by StatSigMA
char SigMAwOutDir[100] = "";
// the prefix of StatSigMA output files
char SigMAwOutPrefix[20] = "";

float* cur_pv;
float* temp_pv;
char* tree_pv;

// human chr
char hgChr[10] = "";
// human coordinates for each alignment column
int* hgCoor;

// arrays of presence and gaps at each position for each branch.
bool** present;
bool** gaps;
// the worst set of species
bool** worst_set;
